using System.Numerics;
using Raylib_cs;

Raylib.SetTargetFPS(60);
Raylib.InitWindow(1400, 900, "SnakeAI");
int pcSc = Raylib.GetCurrentMonitor();
int width = Raylib.GetMonitorHeight(pcSc) - Raylib.GetMonitorHeight(pcSc) / 10;
int height = Raylib.GetMonitorHeight(pcSc) - Raylib.GetMonitorHeight(pcSc) / 10;
int wpx = (Raylib.GetMonitorWidth(pcSc) - width) / 2;
int wpy = (Raylib.GetMonitorHeight(pcSc) - height) / 2;
Raylib.SetWindowSize(width, height);
Raylib.SetWindowPosition(wpx, wpy);
int PWidth = height / 50;
int x = (width / 2) - (PWidth * 20);
int y = (height / 2) - (PWidth * 20);
int font = PWidth / 3;
Vector2[] Platform = new Vector2[1600];
Vector2[] center = new Vector2[1600];
int cc = PWidth / 2;
Random gen = new();
int fc = 0;
bool IsFo = false;
List<int> fp = new List<int>();
List<int> fs = new List<int>();
float timer = 0;
Vector2 pp = new Vector2(20, 800);
Vector2 speed = new Vector2(-1, 0);
Vector2 lp = new Vector2(0, 0);
Vector2[] ll = new Vector2[1600];
int score = 0;
int f = 1599;
bool scorebreach = false;
for (var i = 0; i < 1600; i++)
{
    Platform[i] = new Vector2(x, y);
    center[i] = new Vector2(Platform[i].X + cc, Platform[i].Y + cc);
    x += PWidth;
    if ((i + 1) % 40 == 0)
    {
        y += PWidth;
        x = (width / 2) - (PWidth * 20);
    }
}

while (!Raylib.WindowShouldClose())
{
    Rectangle[] Player = new Rectangle[1600];
    Vector2 startPos = new Vector2(Platform[(int)pp.X].X, Platform[(int)pp.Y].Y);
    if (score < 1599)
    {
        move();
    }
    Player[0] = new Rectangle(startPos.X, startPos.Y, PWidth, PWidth);
    Vector2 mousePos = Raylib.GetMousePosition();
    Raylib.BeginDrawing();
    Raylib.ClearBackground(Color.BLACK);
    for (var i = 0; i < Platform.Length; i++)
    {
        Rectangle square = new(Platform[i].X, Platform[i].Y, PWidth, PWidth);
        Raylib.DrawRectangleRec(square, Color.GREEN);
        Raylib.DrawRectangleLinesEx(square, 1, Color.WHITE);
    }
    int c = 0;
    if (!IsFo && fc == 0)
    {
        for (var i = 0; i < 25; i++)
        {
        fp.Add(1);
        fs.Add(1);
        }
        c = 0;
        for (var i = 0; i < 25; i++)
        {
            int l = gen.Next(30, 1590);
            if (l % 40 == 0)
            {
                fp[i] = l;
            }
            if (fp[i] == 1 || fp[22] == 1)
            {
                c++;
            }
            int j = gen.Next(0, 39);
            fs[i] = j;
        }
        if (c == 0)
        {
            IsFo = true;
            fc = 25;
        }
    }
    if (IsFo)
    {
        for (var i = 0; i < fc; i++)
        {
            Rectangle food = new(center[fs[i]].X - 10, center[fp[i]].Y - 10, 20, 20);
            Raylib.DrawRectangleRec(food, Color.BLUE);
            if (Raylib.CheckCollisionRecs(Player[0], food))
            {
                fp.RemoveAt(i);
                fs.RemoveAt(i);
                fc--;
                score += 1;
            }
        }
        if (fc <= 0)
        {
            IsFo = false;
        }
    }
    Raylib.DrawText($"Score:{score}/400", 10, 10, 30, Color.WHITE);
    Raylib.DrawText("SnakeAI", (width / 2) - (Raylib.MeasureText("SnakeAI", height / 8) / 2), 5, height / 8, Color.VIOLET);
    int yy = 100;
    for (var i = 0; i < fs.Count; i++)
    {
        Raylib.DrawText($"{fs[i]}, {fp[i]}", 10, yy, 30, Color.WHITE);
        yy += 40;
    }
    for (var i = 0; i < score + 1; i++)
    {
        if (i > 0)
        {
            Player[i] = new Rectangle(Platform[(int)ll[i - 1].X].X, Platform[(int)ll[i - 1].Y].Y, PWidth, PWidth);
        }
    }
    for (var i = 0; i < Player.Length; i++)
    {
        if (i < 255)
        {
            Color q = new(255 - i, 0, 0 + i, 255);
            Raylib.DrawRectangleRec(Player[i], q);
        }
        else if (i < 510)
        {
            Color q = new(0, 0 + (i - 255), 255 - (i - 255), 255);
            Raylib.DrawRectangleRec(Player[i], q);
        }
        else if (i < 765)
        {
            Color q = new(0 + (i - 510), 255 - (i - 510), 0, 255);
            Raylib.DrawRectangleRec(Player[i], q);
        }
        else if (i < 1020)
        {
            Color q = new(255, 0 + (i - 765), 0 + (i - 765), 255);
            Raylib.DrawRectangleRec(Player[i], q);
        }
        else
        {
            Raylib.DrawRectangleRec(Player[i], Color.WHITE);
        }
        Raylib.DrawRectangleRec(Player[0], Color.YELLOW);
        Raylib.DrawRectangleLinesEx(Player[i], 1, Color.BLACK);
    }
    Raylib.EndDrawing();
}

void move()
{
    timer += Raylib.GetFrameTime();
    if (timer > 0.201f)
    {
        lp = pp;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        f--;
        ll[f] = ll[f - 1];
        ll[0] = lp;
        lp += speed;
        if (score < 100 && IsFo)
        {
            Vector2 target = new(190, fp[0]);
            if (lp.Y < 10 || lp.Y > 1590)
            {
                lp -= speed;
                speed = new(1, 0);
                pp += speed;
            }
            else if (pp.Y < target.Y)
            {
                lp -= speed;
                speed = new(0, 40);
                pp += speed;
            }
            else if (pp.Y > target.Y)
            {
                lp -= speed;
                speed = new(0, -40);
                pp += speed;
            }
            else if (pp.Y == target.Y && pp.X == 39)
            {
                lp -= speed;
                speed = new(-1, 0);
                pp += speed;
            }
            else if (pp.Y == target.Y && pp.X == 0)
            {
                lp -= speed;
                speed = new(1, 0);
                pp += speed;
            }
            else if (pp.Y == target.Y && speed.X == 0)
            {
                lp -= speed;
                speed = new(1, 0);
                pp += speed;
            }
            else if (pp.Y == 10)
            {
                lp -= speed;
                speed = new(1, 0);
                pp += speed;
            }
            else
            {
                lp -= speed;
                pp += speed;
            }
        }
        if (score >= 100)
        {
            if (!scorebreach)
            {
                if (pp.Y % 80 == 0)
                {
                    speed = new(1, 0);
                    scorebreach = true;
                }
                else if (!(pp.Y % 80 == 0))
                {
                    speed = new(-1, 0);
                    scorebreach = true;
                }
            }
            if (lp.X == 40)
            {
                lp -= speed;
                speed = new(0, 40);
                pp += speed;
                speed = new(-1, 0);
            }
            else if (lp.X == 0 && lp.Y / pp.Y == 1 && lp.Y != 1560)
            {
                lp -= speed;
                speed = new(0, 40);
                pp += speed;
                speed = new(1, 0);
            }
            else if (lp.X == -1 && lp.Y != -10)
            {
                lp -= speed;
                speed = new(0, -40);
                pp += speed;
            }
            else if (lp.X == 0 && lp.Y <= -10)
            {
                lp -= speed;
                speed = new(1, 0);
                pp += speed;
            }
            else
            {
                pp += speed;
            }
        }
        timer = 0.2f;
        f = 1599;
    }
}